version: '3.8'

services:
  # Next.js アプリケーション
  code-explainer-app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - N8N_WEBHOOK_URL=${N8N_WEBHOOK_URL:-https://YOUR_N8N_WEBHOOK_URL}
    networks:
      - app-network
    restart: unless-stopped

  # n8n サービス（オプション）
  # 実際の運用ではn8nが別サーバーにある場合が多いため、コメントアウト
  # n8n:
  #   image: n8nio/n8n:latest
  #   ports:
  #     - "5678:5678"
  #   environment:
  #     - N8N_BASIC_AUTH_ACTIVE=true
  #     - N8N_BASIC_AUTH_USER=admin
  #     - N8N_BASIC_AUTH_PASSWORD=your-secure-password
  #   volumes:
  #     - n8n_data:/home/node/.n8n
  #   networks:
  #     - app-network
  #   restart: unless-stopped

networks:
  app-network:
    driver: bridge

# volumes:
#   n8n_data: